name: Build and deploy Node.js app to Azure Web App - TravelsofSharic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEF1278B581A4ED18032DCA4279EF6E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_06F64FEEC28B4699B1531DE712A208B0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C9146CB47D945B2849AA2DC7A2355E9 }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TravelsofSharic'
          slot-name: 'Production'
          package: .

         
